// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmo1u5tG_T_xKK8k6I5KMbzJscqvvQLrw',
    appId: '1:280619809662:android:ed66fb33eed9788a11912f',
    messagingSenderId: '280619809662',
    projectId: 'chat-g-27',
    storageBucket: 'chat-g-27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-GGLJNfOnA41-G1XrsUhClssahItO8Vs',
    appId: '1:280619809662:ios:0e4450dc5e37e43311912f',
    messagingSenderId: '280619809662',
    projectId: 'chat-g-27',
    storageBucket: 'chat-g-27.appspot.com',
    androidClientId: '280619809662-j9t8vso6v8h3q5esvti9at2q3rnq6pkm.apps.googleusercontent.com',
    iosClientId: '280619809662-i6gfjdqfe2097v3i59kag0tbtggl6prh.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.chatapp',
  );
}
